<?php

/**
 * This file was autogenerated by exporter.
 * @property integer id
 * @property string ip
 * @property DateTime when
 * @property string what

 * @method ActionsLog open() Find and open a record based on primary key.
 * @method ActionsLog create() Create a new record and return object.
 */
class ActionsLog extends DB_Record
{
  public static $table = "actions_log";

  public static $fields = array(
    'id' => array('pk' => true,'ai' => true,),
    'ip' ,
    'when' => array('type' => 'datetime',),
    'what' ,

  );
}
