<?php

/**
 * This file was autogenerated by exporter.
 * @property string tag
 * @property string color
 * @property string title

 * @method Category open() Find and open a record based on primary key.
 * @method Category create() Create a new record and return object.
 */
class Category extends DB_Record
{
  public static $table = "categories";

  public static $fields = array(
    'tag' => array('pk' => true,),
    'color' ,
    'title' ,

  );
  
  /**
   * Get all the categories in an associative array 
   */
  public static function open_all_to_array()
  {
  	$categories = array();
	foreach(Category::open_all() as $cat)
		$categories[$cat->tag] = $cat->toArray();
	return $categories;
  }
}

Category::many_to_many('Place', 'PlacesCats', 'categories', 'places');