<?php

/**
 * This file was autogenerated by exporter.
 * @property integer id
 * @property string name
 * @property integer country_id

 * @method Cities open() Find and open a record based on primary key.
 * @method Cities create() Create a new record and return object.
 */
class Cities extends DB_Record
{
  public static $table = "cities";

  public static $fields = array(
    'id' => array('pk' => true,'ai' => true,),
    'name' ,
    'country_id' ,

  );
}
