<?php

/**
 * This file was autogenerated by exporter.
 * @property integer id
 * @property string name

 * @method Continents open() Find and open a record based on primary key.
 * @method Continents create() Create a new record and return object.
 */
class Continents extends DB_Record
{
  public static $table = "continents";

  public static $fields = array(
    'id' => array('pk' => true,'ai' => true,),
    'name' ,

  );
}
