<?php

/**
 * This file was autogenerated by exporter.
 * @property integer id
 * @property string name
 * @property string iso3166
 * @property integer continent_id

 * @method Countries open() Find and open a record based on primary key.
 * @method Countries create() Create a new record and return object.
 */
class Countries extends DB_Record
{
  public static $table = "countries";

  public static $fields = array(
    'id' => array('pk' => true,'ai' => true,),
    'name' ,
    'iso3166' ,
    'continent_id' ,

  );
}
