<?php

/**
 * This file was autogenerated by exporter.
 * @property string cat_tag
 * @property integer place_id

 * @method PlacesCats open() Find and open a record based on primary key.
 * @method PlacesCats create() Create a new record and return object.
 */
class PlacesCats extends DB_Record
{
  public static $table = "places_cats";

  public static $fields = array(
    'cat_tag' => array('pk' => true, 'fk' => 'Category'),
    'place_id' => array('pk' => true, 'fk' => 'Place'),
  );
}
