<?php

/**
 * This file was autogenerated by exporter.
 * @property string username
 * @property string password
 * @property integer enabled

 * @method User open() Find and open a record based on primary key.
 * @method User create() Create a new record and return object.
 */
class User extends DB_Record
{
	public static $table = "users";

	public static $fields = array(
	    'username' => array('pk' => true,),
	    'password' ,
	    'enabled'
    );

    public static function hash_function($password, $user) {
    	return sha1($password);
    }
}
