<?php

/**
 * This file was autogenerated by exporter.
 * @property string username
 * @property string password
 * @property integer enabled

 * @method Users open() Find and open a record based on primary key.
 * @method Users create() Create a new record and return object.
 */
class Users extends DB_Record
{
  public static $table = "users";

  public static $fields = array(
    'username' => array('pk' => true,),
    'password' ,
    'enabled'
	);
}
