#!/usr/bin/env php
<?php
require_once(__DIR__ . '/bootstrap.php');

function camelize($lowerCaseAndUnderscoredWord) {
	return str_replace(" ", "", ucwords(str_replace("_", " ", $lowerCaseAndUnderscoredWord)));
}


$tables = DB_Conn::query_fetch_all('SHOW TABLES');


foreach($tables as $tb_rec)
{
	$table = $tb_rec[0];
	$class = camelize($table);
	echo 'Table: "' . $table ."\" \n";
	echo "-----------------------------------------------------\n";
	$columns = DB_Conn::query_fetch_all("DESC `{$table}`");
	
	$columns_formated = '';
	$columns_comment = '';
	foreach($columns as $col_rec)
	{
		$column_formated = '';
		$php_type = 'string';
		$props = array();
		$column = $col_rec['Field'];
		if ($col_rec['Key'] == 'PRI' )
			$props['pk'] = true;
		if ($col_rec['Extra'] == 'auto_increment' )
			$props['ai'] = true;
		if ($col_rec['Default'] !== null)
			$props['default'] = $col_rec['Default'];
		if ($col_rec['Type'] == 'datetime') {
			$props['type'] = 'datetime';
			$php_type = 'DateTime';
		} elseif (substr($col_rec['Type'], 0, 3) == 'int') {
			$php_type = 'integer';
		}
		$column_formated = "    '{$col_rec['Field']}' ";
		if (!empty($props))
		{
			$column_formated .= "=> array(";
			foreach($props as $key => $value)
			{
				$column_formated .= "'$key' => ";
				if (is_bool($value))
					$column_formated .= $value?'true':'false';
				else
				    $column_formated .= "'{$value}'";
				$column_formated .= ",";
			}
			$column_formated .= ")";
		} 
		$column_formated .= ",\n";
		$columns_formated .= $column_formated;
		
		$columns_comment .= " * @property {$php_type} {$column}\n";
	}
ob_start();
echo <<< EOF
<?php

/**
 * This file was autogenerated by exporter.
{$columns_comment}
 * @method {$class} open() Find and open a record based on primary key.
 * @method {$class} create() Create a new record and return object.
 */
class {$class} extends DB_Record
{
  public static \$table = "{$table}";

  public static \$fields = array(
{$columns_formated}
  );
}

EOF;
$filedata = ob_get_contents();
ob_end_clean();

$fname = __DIR__ . "/lib/models/{$class}.class.php";
if (file_exists($fname))
	$fname = $fname . ".new.php";
file_put_contents($fname, $filedata);
}

